
/* ------- Challenges -------- */
export const DELETE_CHALLENGE = 'DELETE_CHALLENGE'; //is this used??

export const GET_ALL_CHALLENGES = 'GET_ALL_CHALLENGES';

export const GET_DEFAULT_CHALLENGES = 'GET_DEFAULT_CHALLENGES';

export const SAVE_CHALLENGE = 'SAVE_CHALLENGE'; //is this used?

export const GET_INITIAL_CHALLENGE = 'GET_INITIAL_CHALLENGE';

export const SET_CURRENT_LIVE_CHALLENGE = 'SET_CURRENT_LIVE_CHALLENGE';

export const GET_CHALLENGE_ID = 'GET_CHALLENGE_ID';

/* -------- Authentication -------- */
export const SAVE_COMPANY = 'SAVE_COMPANY';

export const SAVE_CANDIDATE = 'SAVE_CANDIDATE';

export const CHECK_USER = 'CHECK_USER';

export const GET_USER = 'GET_USER';

export const GET_COMPANY_INFO = 'GET_COMPANY_INFO';

/* --------- Calendar --------- */
export const UPDATE_USER_CALENDAR = 'UPDATE_USER_CALENDAR'; //IS THIS USED?

export const UPDATE_COMPANY_CALENDAR = 'UPDATE_COMPANY_CALENDAR'; //IS THIS USED?

export const GET_COMPANY_LIST = 'GET_COMPANY_LIST';

export const DELETE_FROM_COMPANY_SCHEDULE = 'DELETE_FROM_COMPANY_SCHEDULE'; //IS THIS USED?

export const GET_COMPANY_SCHEDULE = 'GET_COMPANY_SCHEDULE';

export const GET_CHALLENGE_INFO = 'GET_CHALLENGE_INFO';

export const TOGGLE_INITIAL_ON = 'TOGGLE_INITIAL_ON';

export const TOGGLE_INITIAL_OFF = 'TOGGLE_INITIAL_OFF';

export const GET_CANDIDATE_CALENDAR = 'GET_CANDIDATE_CALENDAR';

export const GET_CURRENT_COMPANY_CALENDAR = 'GET_CURRENT_COMPANY_CALENDAR';

export const GET_ALL_COMPANY_CALENDARS = 'GET_ALL_COMPANY_CALENDARS';

/* --------- Results -------- */
export const GET_COMPANY_RESULTS = 'GET_COMPANY_RESULTS';

export const GET_CANDIDATE_RESULTS = 'GET_CANDIDATE_RESULTS';

export const SAVE_RESULTS = 'SAVE_RESULTS'; //IS THIS USED?

export const GET_CANDIDATE_LIST = 'GET_CANDIDATE_LIST';

export const GET_CANDIDATE_INITIAL_RESULTS = 'GET_CANDIDATE_INITIAL_RESULTS';

export const GET_ALL_RESULTS = 'GET_ALL_RESULTS';
/* -------- User Profile ------- */
export const GET_CANDIDATE_INFO = 'GET_CANDIDATE_INFO';

export const GET_FAVORITES = 'GET_FAVORITES';

export const SEARCH_USERS = 'SEARCH_USERS';

export const GET_RESUME = 'GET_RESUME';