INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Admin', 'Admin', null, 'admin', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Google', 'Google', 'You know who we are.', 'https://yt3.ggpht.com/a-/AJLlDp0TFaxkKTbr1YMaEdj0KOLllMoFJcuWOIm4XA=s900-mo-c-c0xffffffff-rj-k-no', 'company', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Facebook', 'Facebook', 'We make stalking easy.', 'https://en.facebookbrand.com/wp-content/uploads/2016/05/flogo_rgb_hex-brc-site-250.png', 'company', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Airbnb', 'Airbnb', 'Homeless? We can help.', 'https://www-us.api.concursolutions.com/appcenter/api/v3/listings/550353cc99066b13221bce40/images/57e957ffb490ec6ac904e88e?lang=en-us', 'company', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Slack', 'Slack', 'Unfortunately your workspace doesn’t have any storage space left. To get more space, you can upgrade to a paid account', 'https://cdn-images-1.medium.com/max/1200/1*TiKyhAN2gx4PpbOsiBhYcw.png', 'company', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('Uber', 'Uber', 'Definitely not Lyft',  'https://d1a3f4spazzrp4.cloudfront.net/uber-com/1.3.8/d1a3f4spazzrp4.cloudfront.net/images/uber-serp-logo-f6e7549c89.jpg', 'company', 'test');
INSERT INTO users (name, username, information, logo_url, role, token) VALUES ('LinkedIn', 'LinkedIn', "Can't promise we'll find you a job",  'https://yt3.ggpht.com/a-/AJLlDp0mRnZ39CP7Z0TUWTkjT5WckBX8fB4BTfMAMg=s900-mo-c-c0xffffffff-rj-k-no', 'company', 'test');

INSERT INTO all_challenges (title, instruction, function_name, parameters, test_cases, examples, difficulty, category, initial, duration, company_id) VALUES ('Palindrome Number', 'Determine whether an integer is a palindrome. An integer is a palindrome when it reads the same backward as forward.', 'isPalindrome', 'x', '[[[]], [[]]]', '[[[121, 10]], [[true, false]]]', '1', 'algorithms', false, 30, 1);
INSERT INTO all_challenges (title, instruction, function_name, parameters, test_cases, examples, difficulty, category, initial, duration, company_id) VALUES ('Two Sum', 'Find the sum...', 'twoSum', 'arr, target', '[[[]], [[]]]', '[[[]], [[]]]', '2', 'data structures', false, 30, 1);
INSERT INTO all_challenges (title, instruction, function_name, parameters, test_cases, examples, difficulty, category, initial, duration, company_id) VALUES ('Three Sum', 'Find the sum...', 'threeSum', 'arr, target', '[[[]], [[]]]', '[[[]], [[]]]', '3', 'algorithms', false, 30, 1);

